name: Publish streetmix docker images

on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    branches:
      - master


jobs:
  push_to_registry:
    name: Push streetmix docker images to GitHub Packages
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Build and push streetmix docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: Institute-FVV/streetmix/streetmixdocker
          dockerfile: Dockerfile
          target: streetmix
      -
        name: Build and push streetmix-postgres docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: Institute-FVV/streetmix/streetmixdocker-postgres
          dockerfile: Dockerfile
          target: streetmix-postgres
